### Лабораторная работа №2. Реализация метода главных компонент (PCA)

#### Импорты

In [231]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import plotly.graph_objects as go

#### Загрузка набора данных

In [175]:
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [176]:
X = data.data
y = data.target

In [177]:
feature_names = data.feature_names

In [178]:
X.shape, y.shape

((569, 30), (569,))

In [179]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [180]:
X_df = pd.DataFrame(X, columns=feature_names)
X_df.head()

   mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [181]:
X_df.describe()

       mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

#### Реализация алгоритма PCA

In [182]:
def my_pca(X: np.ndarray, k: int):
    # Центрирование данных
    X_centered = X - X.mean(axis=0)
    # Построение ковариационной матрицы
    C = np.cov(X_centered, rowvar=False)
    # Диагонализация матрицы
    eigvals, eigvecs = np.linalg.eig(C)
    # Сортировка компонент
    sorted_indices = np.argsort(eigvals)[::-1]
    eigvals_sorted = eigvals[sorted_indices]
    eigvecs_sorted = eigvecs[:, sorted_indices]
    # Доля объясненной дисперсии
    explained_variance_ratio = eigvals_sorted / np.sum(eigvals_sorted)
    # Выбор K главных компонент
    W_K = eigvecs_sorted[:, :k]
    # Проекция данных
    Z = X_centered @ W_K
    # Возврат результата
    return Z, eigvals_sorted, explained_variance_ratio

#### Применение PCA

In [183]:
Z2_manual, exp_variance_manual, exp_variance_ratio_manual = my_pca(X, 2)
f'{Z2_manual.shape=}'

'Z2_manual.shape=(569, 2)'

In [184]:
pca_sk = PCA(n_components=2)
Z2_sklearn, exp_variance_sklearn, exp_variance_ratio_sklearn = pca_sk.fit_transform(X), pca_sk.explained_variance_, pca_sk.explained_variance_ratio_
f'{Z2_sklearn.shape=}'

'Z2_sklearn.shape=(569, 2)'

#### Сравнение реализаций

In [185]:
print(f'{exp_variance_manual[:2]=}')
print(f'{exp_variance_sklearn=}')
print(f'{exp_variance_ratio_manual[:2]=}')
print(f'{exp_variance_ratio_sklearn=}')

exp_variance_manual[:2]=array([443782.6051466 ,   7310.10006165])
exp_variance_sklearn=array([443782.6051466 ,   7310.10006165])
exp_variance_ratio_manual[:2]=array([0.98204467, 0.01617649])
exp_variance_ratio_sklearn=array([0.98204467, 0.01617649])

In [246]:
components_2 = [1, 2]

bar_char_fit = go.Figure()
bar_char_fit.add_trace(
    go.Bar(name='Z2_manual', x=components_2, y=exp_variance_ratio_manual[:2])
)
bar_char_fit.add_trace(
    go.Bar(name='Z2_sklearn', x=components_2, y=exp_variance_ratio_sklearn)
)
bar_char_fit.update_layout(
    barcornerradius=15,
    barmode='group'
)
bar_char_fit.update_layout(
    title='Доля объясненной дисперсии компонент по наборам данных',
    xaxis_title='Компонента',
    yaxis_title='Доля объясненной дисперсии',
    legend=dict(
        title='Набор данных:',
    ),
)
bar_char_fit.show()

In [245]:
scatter_plot_fig = go.Figure()
scatter_plot_fig.add_trace(
    go.Scatter(
        x=Z2_manual[:, 0],
        y=Z2_manual[:, 1],
        mode='markers',
        name='Z2_manual'
    )
)
scatter_plot_fig.add_trace(
    go.Scatter(
        x=Z2_sklearn[:, 0],
        y=Z2_sklearn[:, 1],
        mode='markers',
        name='Z2_sklearn'
    )
)
scatter_plot_fig.update_layout(
    title='Распределение значений двух главных компонент по наборам данных',
    xaxis_title='Значение 1 компоненты',
    yaxis_title='Значение 2 компоненты',
    legend=dict(
        title='Набор данных:',
    ),
)
scatter_plot_fig.show()

#### Выбор оптимального числа компонент

In [244]:
components = [i for i in range(1, len(exp_variance_ratio_manual) + 1)]

scree_plot_fig = go.Figure()
scree_plot_fig.add_trace(
    go.Bar(name='bars', x=components, y=exp_variance_ratio_manual)
)
scree_plot_fig.add_trace(
    go.Scatter(name='lines', x=components, y=exp_variance_ratio_manual, mode='lines+markers')
)
scree_plot_fig.update_layout(
    title='График осыпи (Scree plot)',
    xaxis_title='Номер компоненты',
    yaxis_title='Значение дисперсии',
    legend=dict(
        title='Значения:',
    ),
)
scree_plot_fig.show()

In [242]:
threshold = 0.999
cumulative = np.cumsum(exp_variance_ratio_manual)
threshold_line = [threshold for _ in range(len(exp_variance_ratio_manual))]

cumulative_fig = go.Figure()
cumulative_fig.add_trace(
    go.Scatter(name='Компонента', x=components, y=cumulative, mode='lines+markers')
)
cumulative_fig.add_trace(
    go.Scatter(name='Порог', x=components, y=threshold_line, mode='lines')
)
cumulative_fig.update_layout(
    title='График накопления объясненной дисперсии',
    xaxis_title='Номер компоненты',
    yaxis_title='Соотношение дисперсии',
    legend=dict(
        title='Значения:',
    ),
)
cumulative_fig.show()

In [240]:
malignant_val = np.array([v for i, v in enumerate(Z2_manual) if y[i] == 0])
benign_val = np.array([v for i, v in enumerate(Z2_manual) if y[i] == 1])

class_scatter_plot_fig = go.Figure() 
class_scatter_plot_fig.add_trace(
    go.Scatter(
        x=malignant_val[:, 0],
        y=malignant_val[:, 1],
        mode='markers',
        name='malignant'
    )
)
class_scatter_plot_fig.add_trace(
    go.Scatter(
        x=benign_val[:, 0],
        y=benign_val[:, 1],
        mode='markers',
        name='benign'
    )
)
class_scatter_plot_fig.update_layout(
    title='Распределение значений двух главных компонент по классам',
    xaxis_title='Значение 1 компоненты',
    yaxis_title='Значение 2 компоненты',
    legend=dict(
        title='Класс:',
    ),
)
class_scatter_plot_fig.show()

#### Эксперимент с Lasso

In [216]:
# Признаки должны быть стандартизованы для одинаковых штрафов относительно друг друга
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [238]:
alpha_range = np.arange(0.1, 0.5, 0.0001)
coefs = []

for alpha in alpha_range:
    l1_model = Lasso(alpha=alpha)
    l1_model.fit(X_scaled, y)
    coefs.append(l1_model.coef_)

coefs = np.array(coefs)

In [239]:
l1_coefs_fig = go.Figure()
for i in range(X.shape[1]):
    l1_coefs_fig.add_trace(
        go.Scatter(
            x=alpha_range,
            y=coefs[:, i],
            name=feature_names[i],
            mode='lines'
        )
    )
l1_coefs_fig.update_layout(
    title='Веса признаков в зависимости от степени l1-регуляризации',
    xaxis_title='Коэффициент l1-регуляризации',
    yaxis_title='Вес признака',
    legend=dict(
        title='Признак:',
    ),
)
l1_coefs_fig.show()

#### Обучение и сравнение моделей логистической регрессии

In [193]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [194]:
unique_counts_train = np.unique_counts(y_train)
unique_counts_train

UniqueCountsResult(values=array([0, 1]), counts=array([145, 236]))

In [195]:
unique_counts_test = np.unique_counts(y_test)
unique_counts_test

UniqueCountsResult(values=array([0, 1]), counts=array([ 67, 121]))

In [211]:
bar_char_fit = go.Figure()
bar_char_fit.add_trace(
    go.Bar(name='Train', x=unique_counts_train.values, y=unique_counts_train.counts)
)
bar_char_fit.add_trace(
    go.Bar(name='Test', x=unique_counts_test.values, y=unique_counts_test.counts)
)
bar_char_fit.update_layout(
    title='Распределение классов по наборам данных',
    xaxis_title='Класс',
    yaxis_title='Количество элементов',
    legend=dict(
        title='Набор данных:',
    ),
    barcornerradius=15,
    barmode='group'
)
bar_char_fit.show()

In [197]:
# Для избежания утечки данных (data leakage)
new_pca_sk = PCA(n_components=2).fit(X_train)
X_train_pca = new_pca_sk.transform(X_train)
X_test_pca = new_pca_sk.transform(X_test)

In [198]:
iter_num = 10000
logreg = LogisticRegression(max_iter=iter_num)
logreg_pca = LogisticRegression(max_iter=iter_num)

In [199]:
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [200]:
logreg_pca.fit(X_train_pca, y_train)

LogisticRegression(max_iter=10000)

In [201]:
pred_logreg_train = logreg.predict(X_train)
pred_logreg_test = logreg.predict(X_test)
f1_logreg_train = f1_score(y_train, pred_logreg_train)
f1_logreg_test = f1_score(y_test, pred_logreg_test)

In [202]:
pred_logreg_pca_train = logreg_pca.predict(X_train_pca)
pred_logreg_pca_test = logreg_pca.predict(X_test_pca)
f1_logreg_pca_train = f1_score(y_train, pred_logreg_pca_train)
f1_logreg_pca_test = f1_score(y_test, pred_logreg_pca_test)

In [212]:
f1_list = [
    [f1_logreg_train, f1_logreg_test],
    [f1_logreg_pca_train, f1_logreg_pca_test]
]

heatmap_fig = go.Figure(
    go.Heatmap(
        x=['Train', 'Test'],
        y=['logreg', 'logreg_pca'],
        z=f1_list,
        text=np.round(f1_list, 3),
        texttemplate='%{text}',
        colorscale = 'ylgn',
    )
)
# Настраиваем макет
heatmap_fig.update_layout(
    title='Тепловая карта оценки F1-score (модель, набор данных)',
    xaxis_title='Набор данных',
    yaxis_title='Модель',
)
heatmap_fig.show()